### ISSUE TITLE
Add wifi room check

### ISSUE THREAD

**Issue by chbjerre** [christianknu/eitu#3]
Use the Wifi API from Jacob Cholewa to fetch wifi data:
http://training.itu.dk:8080/api/rooms
http://training.itu.dk:8080/api/occupancy
http://training.itu.dk:8080/api/occupancy/34
http://training.itu.dk:8080/api/history
http://training.itu.dk:8080/api/history/34

**Comment by christianknu** [comment]
Consider saving the data in a local database (sqlite).

**Comment by chbjerre** [comment]
Also working on adding the json to a database, where the database is updated regularly

**Comment by chbjerre** [comment]
Global variable checked to see if database data is stale
